[Grpc]
  Listen = "0.0.0.0:12345"

[Http]
  Listen = "0.0.0.0:12346"
  HSKey = "memo.io"
  CookieExpire = 86400

[Local]
  KVDBPath = "./kvdb"
  SignExpire = 86400

[Remote]
  KeyStore = "./.keystore"
  Wallet = "0xEf95c72C836605203F7f66788E450Af2a4141957"

[Platform]
  Url = "http://183.240.197.189:18002"
  
[Validator]
  Url = "http://localhost:8081"