[Grpc]
Listen = "0.0.0.0:12345"

[Http]
# computing backend
Listen = "0.0.0.0:12346"
# key to sign for cookie
HSKey = "memo.io"
# cookie's expire timestamp
Expire = 86400

[Local]
DBPath = "./testdb"
# expire for signature in type2
SignExpire = 86400000

[Remote]
Wallet = "0x123456"
