apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-example
    app/clean: label-for-clean
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-example
    spec:
      containers:
      - name: hello-world
        image: gcr.io/google-samples/node-hello:1.0
        #image: docker.io/rockiecn/hello-app:2.0
        #imagePullPolicy: Never
        ports:
        - containerPort: 8080
