---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:       
      app.kubernetes.io/name: mefs-provider
      app/clean: label-for-clean      
  name: provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mefs-provider
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mefs-provider
    spec:
      nodeSelector:
        kubernetes.io/hostname: m20
      initContainers:
      - name: init-provider
        image: webserver_provider_test_auto:latest
        imagePullPolicy: IfNotPresent
        command: [ "sh", "-c" ]
        args:
        - |
          mkdir -p /root/memo_provider &&
          mkdir -p /root/memo_provider_data &&
          echo "/root/memo_provider and /root/memo_provider_data directory created!" &&
          /app/init_provider.sh > /root/memo_provider/log ;  # 执行脚本
        volumeMounts:
        - name: memo-provider-volume
          mountPath: /root  # 容器内部的挂载路径
      
      terminationGracePeriodSeconds: 60    
      containers:
      - name: mefs-provider
        image: webserver_provider_test_auto:latest  # Use your Docker image
        imagePullPolicy: IfNotPresent
        ports:
           - containerPort: 4001
           - containerPort: 8081

        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "rm -rf /root/memo_provider && rm -rf /root/memo_provider_data"]     

        env:
           - name: PASSWORD
             value: "memoriae"     
           - name: PRICE
             value: "250000"
           - name: GROUP
             value: "1"    
           - name: MEFS_PATH
             value: "/root/memo_provider/.memo-provider"
           - name: SWARM_PORT
             value: "4001"
           - name: DATA_PATH
             value: "/root/memo_provider_data"
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
        volumeMounts:
            - name: memo-provider-volume
              mountPath: /root  # Path inside the container for models
      volumes:
        - name: memo-provider-volume
          hostPath:
            path: /root/memo  # Host path to models
            type: DirectoryOrCreate


---
apiVersion: v1
kind: Service
metadata:
  name: provider-service
spec:
  selector:
     app.kubernetes.io/name: mefs-provider
  ports:
   - name: provider
     protocol: TCP
     port: 4001
     targetPort: 4001
     nodePort: 32041
   - name: webserver
     protocol: TCP
     port: 8081
     targetPort: 8081
     nodePort: 32027
  type: NodePort