---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:       
      app.kubernetes.io/name: mefs-provider
      app/clean: label-for-clean      
  name: provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mefs-provider
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mefs-provider
    spec:
      nodeSelector:
        kubernetes.io/hostname: m20
      containers:
      - name: mefs-provider
        image: webserver_provider:latest  # Use your Docker image
        imagePullPolicy: IfNotPresent
        ports:
           - containerPort: 4001
           - containerPort: 8081
        env:
           - name: PASSWORD
             value: "memoriae"     
           - name: PRICE
             value: "250000"
           - name: GROUP
             value: "4"    
           - name: MEFS_PATH
             value: "/root/.memo-provider"
           - name: SWARM_PORT
             value: "4001"
           - name: DATA_PATH
             value: "/root/data"
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
        volumeMounts:
            - name: mefs-path
              mountPath: /root  # Path inside the container for models
            - name: mefs-data
              mountPath: /root/data  # Path inside the container for outputs
      volumes:
        - name: mefs-path
          hostPath:
            path: /root/memo_provider  # Host path to models
            type: Directory
        - name: mefs-data
          hostPath:
            path: /root/memo_provider_data  # Host path for outputs
            type: Directory


---
apiVersion: v1
kind: Service
metadata:
  name: provider-service
spec:
  selector:
     app.kubernetes.io/name: mefs-provider
  ports:
   - name: provider
     protocol: TCP
     port: 4001
     targetPort: 4001
     nodePort: 32041
   - name: webserver
     protocol: TCP
     port: 8081
     targetPort: 8081
     nodePort: 32027
  type: NodePort