apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: nginx-example
    app/clean: label-for-clean
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-example
    spec:
      containers:
      - image: docker.io/library/nginx:latest
        name: nginx
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "16Mi"
            cpu: "250m"
          limits:
            memory: "32Mi"
            cpu: "500m"
      nodeSelector:
        id: "1"