apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ubuntu-example
  name: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-example
  template:
    metadata:
      labels:
        app: ubuntu-example
    spec:
      containers:
      - name: ubuntu
        image: docker.io/library/ubuntu:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
